"""Add Contact model

Revision ID: 8de9f530e024
Revises: f3b73b98ffd2
Create Date: 2025-12-29 20:37:01.626741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8de9f530e024'
down_revision = 'f3b73b98ffd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('company', sa.String(length=200), nullable=True),
    sa.Column('job_title', sa.String(length=100), nullable=True),
    sa.Column('account_tier', sa.String(length=20), nullable=True),
    sa.Column('account_status', sa.String(length=20), nullable=True),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('is_vip', sa.Boolean(), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('custom_fields', sa.Text(), nullable=True),
    sa.Column('total_calls', sa.Integer(), nullable=False),
    sa.Column('last_interaction_at', sa.DateTime(), nullable=True),
    sa.Column('average_sentiment', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contacts_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_contacts_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contacts_phone'), ['phone'], unique=True)

    with op.batch_alter_table('calls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('direction', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('handler_type', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('ai_agent_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('sentiment_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ai_context', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_calls_contact_id'), ['contact_id'], unique=False)
        batch_op.create_foreign_key(None, 'contacts', ['contact_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calls', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_calls_contact_id'))
        batch_op.drop_column('ai_context')
        batch_op.drop_column('sentiment_score')
        batch_op.drop_column('ai_agent_name')
        batch_op.drop_column('handler_type')
        batch_op.drop_column('direction')
        batch_op.drop_column('contact_id')

    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contacts_phone'))
        batch_op.drop_index(batch_op.f('ix_contacts_external_id'))
        batch_op.drop_index(batch_op.f('ix_contacts_email'))

    op.drop_table('contacts')
    # ### end Alembic commands ###
