"""Add Call Fabric subscriber fields to User model

Revision ID: f3b73b98ffd2
Revises: 
Create Date: 2025-11-24 23:37:44.668919

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f3b73b98ffd2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agents')
    op.drop_table('queues')
    with op.batch_alter_table('calls', schema=None) as batch_op:
        batch_op.drop_constraint('calls_signalwire_call_sid_key', type_='unique')
        batch_op.drop_index('idx_calls_signalwire_call_sid')
        batch_op.create_index(batch_op.f('ix_calls_signalwire_call_sid'), ['signalwire_call_sid'], unique=True)

    with op.batch_alter_table('transcriptions', schema=None) as batch_op:
        batch_op.drop_constraint('transcriptions_call_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'calls', ['call_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signalwire_subscriber_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('signalwire_username', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('signalwire_password_encrypted', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('signalwire_address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('fabric_subscriber_created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'agent'::character varying"))
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_constraint('users_email_key', type_='unique')
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_signalwire_subscriber_id'), ['signalwire_subscriber_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_signalwire_username'), ['signalwire_username'], unique=True)

    with op.batch_alter_table('webhook_events', schema=None) as batch_op:
        batch_op.drop_constraint('webhook_events_call_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'calls', ['call_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webhook_events', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('webhook_events_call_id_fkey', 'calls', ['call_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_signalwire_username'))
        batch_op.drop_index(batch_op.f('ix_users_signalwire_subscriber_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_unique_constraint('users_email_key', ['email'])
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'agent'::character varying"))
        batch_op.drop_column('fabric_subscriber_created_at')
        batch_op.drop_column('signalwire_address')
        batch_op.drop_column('signalwire_password_encrypted')
        batch_op.drop_column('signalwire_username')
        batch_op.drop_column('signalwire_subscriber_id')

    with op.batch_alter_table('transcriptions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('transcriptions_call_id_fkey', 'calls', ['call_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('calls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calls_signalwire_call_sid'))
        batch_op.create_index('idx_calls_signalwire_call_sid', ['signalwire_call_sid'], unique=False)
        batch_op.create_unique_constraint('calls_signalwire_call_sid_key', ['signalwire_call_sid'])

    op.create_table('queues',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('priority', sa.INTEGER(), server_default=sa.text('5'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='queues_pkey')
    )
    op.create_table('agents',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'offline'::character varying"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='agents_pkey'),
    sa.UniqueConstraint('email', name='agents_email_key')
    )
    # ### end Alembic commands ###
